### PR TITLE
first person maze : ok

### PR DESCRIPTION
**Pull request by jeangit**

### CODE REVIEW

**Comment by greenfork** [comment]
@jeangit you can navigate to "Files changed" tab to see which changes your pull requests proposes. Currently it only deletes `scripts/find_missing_examples.nim` file. You will probably need to read some tutorials on git

**Comment by greenfork** [comment]
You can try this guide https://www.gun.io/blog/how-to-github-fork-branch-and-pull-request

**Comment by greenfork** [comment]
I updated contributing notes, please take a look https://github.com/greenfork/nimraylib_now/blob/master/CONTRIBUTING.md

It should have all things necessary

**Comment by jeangit** [comment]
yes i have followed the guide, but even git gurus were unabled to explain me how to ignore an tracked but already modified file (so included in the cache) except by removing it from the cache (`git rm --cached file`). So that's what i did, but it seems to have removed it on the pushed branch (not on local). git is so odd sometimes, sorry for that i revert things by getting a fresh version of the script, and then pushing it here again.

**Pull request closed without merging**
