### PR TITLE
Add text_font_loading exemple

### PR DESCRIPTION
**Pull request by ryback08**
Add text_font_loading,
Nim translation of https://github.com/raysan5/raylib/blob/master/examples/text/text_font_loading.c

### CODE REVIEW

**Comment by greenfork** [comment]
Hi! Sorry for late reply, I have troubles with internet connection, I will definitely get back to your PRs but it could be tomorrow or another week or more. Thanks for your PRs, I appreciate it!

**Comment by greenfork** [comment]
@ryback08  Looks great! A couple of comments:
- Did you have trouble with `beginDrawing:` block form? It should work, you can see it in other examples
- Could you please run `nimble prepareTests` and then add the tests to this PR as well `git add tests/`? We use examples as tests in our CI

**Comment by ryback08** [comment]
Hello Greenfork

No problem with beginDrawing bloc. I just need remove "endDrawing()".

For the second point, what should I do ? I discover nim/git/raylib, it's not obvious to me, but i try to do the best.

**Comment by greenfork** [comment]
For the second point:
```
cd nimraylib_now
nimble prepareTests
nimble testExamples
git add tests/
git commit -m "Added tests"
```

This will generate tests, run them and commit them. If you don't know `nimble` - it's a build system for Nim https://github.com/nim-lang/nimble. Here I use it to create custom scripts which you can see in `nimraylib_now.nimble`. Do you have any other questions? Feel free to ask.

**Review by greenfork — APPROVED** [review]
This is great, thanks!

**Pull request merged**
