### PR TITLE
Glyphs & recs as UncheckedArray ptr

### PR DESCRIPTION
**Pull request by ryback08**
Hello

I translate : [https://www.raylib.com/examples/text/loader.html?name=text_rectangle_bounds](url)

I have modify Font object with Unchecked Array ptr for "recs" and "glyphs".
I don't know if it is the good solution.

### CODE REVIEW

**Comment by planetis-m** [comment]
The files are autogenerated by src/convert_c_to_nim.nim  Instead you can use the https://github.com/nim-lang/c2nim/blob/master/doc/c2nim.rst#id21 directive to instruct c2nim to produce arrays.

**Comment by planetis-m** [comment]
Actually isarray applies only on proc parameters and not fields, which is a same. A better solution is using c2nim#araq-gobject with support for a custom post processor.

**Comment by greenfork** [comment]
@ryback08 example looks great! A comment about `beginDrawing` - I think we would prefer using its block form, similar comment to your other PR, looks like a more Nim-way. Would you mind changing it?

About `UncheckedArray` change, as @planetis-m said, the bindings are auto-generated, so you would want to modify the https://github.com/greenfork/nimraylib_now/blob/bc021ec423a858b0ce7b9ba44ae94c028aaa6332/src/convert_c_to_nim.nim#L396-L436 lines. If this seems too much, could you please then just remove these changes and I can do them in master branch myself?

**Comment by greenfork** [comment]
@planetis-m it's a good thing about `#isarray` directive, I didn't notice it before. Maybe we can integrate it as well after we decide how to move forward with JSON thing

**Comment by greenfork** [comment]
Great, thanks! I added tests as well. I merged it through git interface, see commits here https://github.com/greenfork/nimraylib_now/commits/master. I'm not yet sure how to modify pull requests properly

**Pull request closed without merging**
